/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/DFzVuOSDLEA
 */
import { Button } from "@/components/ui/button"

export function Home() {
  return (
    (<div className="bg-white">
      <div
        className="bg-[url('/placeholder.svg?height=768&width=1152')] bg-cover bg-no-repeat">
        <div className="container mx-auto py-10 text-center">
          <h1 className="text-4xl font-bold">Welcome to Our Community</h1>
          <p className="mt-4 text-xl">Join us and make a difference!</p>
          <Button className="mt-6" variant="default">
            Get Started
          </Button>
        </div>
      </div>
      <div
        className="&quot;bg-[url('data:image/svg+xml,%3Csvg width='100%' height='100%' xmlns='http://www.w3.org/2000/svg'%3E%3Crect width='100%' height='100%' fill='none'/%3E%3Ccircle cx='50%' cy='10%' r='80' fill='%23e1e1e1'/%3E%3Ccircle cx='90%' cy='20%' r='50' fill='%23e1e1e1'/%3E%3Ccircle cx='30%' cy='30%' r='100' fill='%23e1e1e1'/%3E%3Ccircle cx='80%' cy='60%' r='30' fill='%23e1e1e1'/%3E%3Ccircle cx='20%' cy='70%' r='70' fill='%23e1e1e1'/%3E%3Ccircle cx='50%' cy='90%' r='60' fill='%23e1e1e1'/%3E%3C/svg%3E')]&quot;">
        <div className="container mx-auto py-20">
          <h2 className="text-3xl font-semibold">About Us</h2>
          <p className="mt-4 text-lg">
            We are a vibrant community dedicated to bringing people together and fostering a spirit of collaboration and
            growth.
          </p>
        </div>
      </div>
    </div>)
  );
}
